server:
  port: 8088
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: druid
  devtools:
    restart:
      enabled: true
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  redis:
    host: mpw:7aNhjYryr1lNv1LTpXlbsw==
    port: 63790
    password: mpw:Oyp8+1/4QCgCQIkCWBPm3l7FCPzc8e/4ziO+ZoWGLl8=
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
  rabbitmq:
    host: mpw:7aNhjYryr1lNv1LTpXlbsw==
    port: 5672
    username: mpw:7K5Y8Fa8553zAmOGsEXI7Q==
    password: mpw:85dAFGfDJnsPOUq+IiNTIA==
    listener:
      simple:
        # 并发消费者的初始化值
        concurrency: 10
        # 并发消费者的最大值
        max-concurrency: 20
        # 每个消费者每次监听时可拉取处理的消息数量
        prefetch: 5

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段值
      logic-delete-field: deleteFlag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 全局主键类型
      id-type: assign_uuid
    # 去除控制台logo
    banner: false
  configuration:
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置实体类别名
  type-aliases-package: top.pullulate.**.entity
  # 配置xml信息
  mapper-locations: classpath:/mybatis/mapper/**/*.xml

# 百度开发者账号配置
baidu:
  name: mpw:7K5Y8Fa8553zAmOGsEXI7Q==
  ak: mpw:vPsL8t0CX/CFdqqEDnzy6hBHiYViJ+3JnhTeNCxU8lTfj8F7JBa/c5A1NATgFCKq

# 高德开发者账号配置
gaode:
  name: mpw:7K5Y8Fa8553zAmOGsEXI7Q==
  key: mpw:DeSUhZB6jMUChyC/ZWOIsc0tdkBzZdAtoqnTNReVFa30l9TqAByOk9s+QmTLchwU
  districtUrl: https://restapi.amap.com/v3/config/district?key=