server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: druid
  devtools:
    restart:
      enabled: true
  messages:
    basename: static/i18n/messages
    encoding: UTF-8

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段值
      logic-delete-field: delete_flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 全局主键类型
      id-type: assign_uuid
    # 去除控制台logo
    banner: false
  # 配置通用枚举
  type-enums-package: top.pullulate.common.enums
  configuration:
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    top.pullulate.system: debug