server:
  port: 8088
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: druid
  devtools:
    restart:
      enabled: true
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  redis:
    host: 106.55.165.80
    port: 63790
    password: pullulates123456
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段值
      logic-delete-field: delete_flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 全局主键类型
      id-type: assign_uuid
    # 去除控制台logo
    banner: false
  # 配置通用枚举
  type-enums-package: top.pullulate.common.enums
  configuration:
    #使用驼峰法映射属性,配置这个resultType可以映射
    map-underscore-to-camel-case: true
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # 日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置实体类别名
  type-aliases-package: top.pullulate.system.entity
  # 配置xml信息
  mapper-locations: classpath:/mybatis/mapper/*.xml