# 数据源配置
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      strict: false
      # 数据源信息使用mybatis plus官方提供的加密方式
      datasource:
        master:
          url: mpw:mHD72O8K4lVRygXEwLa1gMRM8ouDlltaZK1D+5KHraf9jbV0kNjG9ZWk0+9Bmh5Jrda7h60jJ/JfmIV0wM5JG2CAVHcEks0nYXRpX8sV4ydRCLRujAd6Rbj2eH8RkEceuAVwYEckRcyN6RDUTGA0eQ==
          username: mpw:Ck3z6mj73rZsoe5HZXe6Sw==
          password: mpw:Oyp8+1/4QCgCQIkCWBPm3l7FCPzc8e/4ziO+ZoWGLl8=
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: mpw:mHD72O8K4lVRygXEwLa1gMRM8ouDlltaZK1D+5KHraf9jbV0kNjG9ZWk0+9Bmh5Jrda7h60jJ/JfmIV0wM5JG2CAVHcEks0nYXRpX8sV4ydRCLRujAd6Rbj2eH8RkEceuAVwYEckRcyN6RDUTGA0eQ==
          username: mpw:Ck3z6mj73rZsoe5HZXe6Sw==
          password: mpw:Oyp8+1/4QCgCQIkCWBPm3l7FCPzc8e/4ziO+ZoWGLl8=
          driver-class-name: com.mysql.cj.jdbc.Driver