org:
  quartz:
    scheduler:
      instanceId: AUTO
      instanceName: pullulateschedule
      rmi:
        export: false
        proxy: false
      wrapJobExecutionInUserTransaction: false
    # 如何存储任务和触发器等信息
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      isClustered: false
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      tablePrefix: qrtz_
      dataSource: quartzDataSource
    #数据源配置
    dataSource:
      quartzDataSource:
        driver: com.mysql.cj.jdbc.Driver
        URL: mpw:mHD72O8K4lVRygXEwLa1gMRM8ouDlltaZK1D+5KHraf9jbV0kNjG9ZWk0+9Bmh5Jrda7h60jJ/JfmIV0wM5JG2CAVHcEks0nYXRpX8sV4ydRCLRujAd6Rbj2eH8RkEceuAVwYEckRcyN6RDUTGA0eQ==
        user: mpw:Ck3z6mj73rZsoe5HZXe6Sw==
        password: mpw:Oyp8+1/4QCgCQIkCWBPm3l7FCPzc8e/4ziO+ZoWGLl8=
        maxConnections: 10